// <auto-generated />
using System;
using Kanoon.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kanoon.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190715171137_UpdateNullable_Heiat_Migration")]
    partial class UpdateNullable_Heiat_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kanoon.DomainModels.Entities.Heiat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alley");

                    b.Property<string>("AndOther");

                    b.Property<bool>("AndOtherSchedule");

                    b.Property<int?>("ApproximatePopulation");

                    b.Property<string>("Area");

                    b.Property<string>("AuxiliaryRoad");

                    b.Property<bool>("Brothers");

                    b.Property<string>("Charity");

                    b.Property<bool>("Const");

                    b.Property<string>("ContactNames");

                    b.Property<string>("ContactPhoneNumber");

                    b.Property<string>("Cultural");

                    b.Property<bool>("EconomicActivitiesInTheField");

                    b.Property<string>("Educational");

                    b.Property<string>("EssentialRequirementsOfTheBoard");

                    b.Property<string>("EstablishedYear");

                    b.Property<bool>("FixedBudgetOrganizationOrOffice");

                    b.Property<bool>("Husseinieh");

                    b.Property<string>("InstagramAddress");

                    b.Property<bool>("IsBreastplate");

                    b.Property<bool>("IsCatering");

                    b.Property<bool>("IsChainsaw");

                    b.Property<bool>("IsDeally");

                    b.Property<bool>("IsEagerness");

                    b.Property<bool>("IsEthnicity");

                    b.Property<bool>("IsGuild");

                    b.Property<bool>("IsLocal");

                    b.Property<bool>("IsMonthly");

                    b.Property<bool>("IsNotificationBar");

                    b.Property<bool>("IsOfficial");

                    b.Property<bool>("IsPassionReading");

                    b.Property<bool>("IsPray");

                    b.Property<bool>("IsQuran");

                    b.Property<bool>("IsResemblance");

                    b.Property<bool>("IsShokhanran");

                    b.Property<bool>("IsWeekly");

                    b.Property<bool>("IsYearly");

                    b.Property<string>("LocArea");

                    b.Property<int>("LocationId");

                    b.Property<string>("Maddah");

                    b.Property<string>("ManagerName");

                    b.Property<string>("ManagerPhoneNumber");

                    b.Property<string>("MediaManagerFullName");

                    b.Property<string>("MediaManagerPhoneNumber");

                    b.Property<bool>("Mobile");

                    b.Property<string>("MonthDay");

                    b.Property<bool>("Mosque");

                    b.Property<string>("Name");

                    b.Property<string>("Others");

                    b.Property<string>("Plaque");

                    b.Property<bool>("PopularSupport");

                    b.Property<int?>("PopulationsInSpecialProgram");

                    b.Property<string>("PrayName");

                    b.Property<bool>("PrivateBuilding");

                    b.Property<string>("Qhari");

                    b.Property<string>("RegistrationLocation");

                    b.Property<int?>("RegistrationNumber");

                    b.Property<string>("SMSSystemNumber");

                    b.Property<bool>("Sisters");

                    b.Property<string>("SiteAddress");

                    b.Property<string>("Sokhanran");

                    b.Property<string>("SpecialApp");

                    b.Property<string>("TelegramAddress");

                    b.Property<bool>("TemporaryPublicSpace");

                    b.Property<string>("TheCamp");

                    b.Property<string>("TheMainStreet");

                    b.Property<string>("TheNeighbourhood");

                    b.Property<int?>("TotalArea");

                    b.Property<int?>("TotalBrother");

                    b.Property<int?>("TotalSister");

                    b.Property<string>("WeekDay");

                    b.Property<string>("YearDay");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Heiat");
                });

            modelBuilder.Entity("Kanoon.DomainModels.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Kanoon.DomainModels.Entities.LocationMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasMaxLength(200);

                    b.Property<int>("LocationId");

                    b.Property<string>("PhoneNumbers");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationMembers");
                });

            modelBuilder.Entity("Kanoon.DomainModels.Entities.Heiat", b =>
                {
                    b.HasOne("Kanoon.DomainModels.Entities.Location", "Location")
                        .WithMany("Heiats")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kanoon.DomainModels.Entities.LocationMember", b =>
                {
                    b.HasOne("Kanoon.DomainModels.Entities.Location", "Location")
                        .WithMany("Members")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
